trigger:
  branches:
    include:
      - master
      - develop
      - feature/azure-pipeline

variables:
  - template: _devops_/pipeline/vars_pipe_global.yaml
  - group: app-eitri-cea-seueitriapp-common
  - ${{ if or(eq(variables['Build.SourceBranchName'], 'master'), contains(variables['Build.SourceBranch'], 'refs/tags/')) }}:
    - group: 'app-eitri-cea-seueitriapp-prd'
  - ${{ else }}:
    - template: _devops_/pipeline/vars_pipe_develop.yaml
    - group: 'app-eitri-cea-seueitriapp-dev'

resources:
  repositories:
  - repository: templates
    type: git
    name: Tech/arq-devops-template-pipelines
    ref: 'refs/heads/feature/eitri-app'

extends:
  template: app/eitri/azure-pipeline.yaml@templates